import json 

my_settings = json.dumps([
    {
        "type": "bool",
        "title": "Enable Audio",
        "desc": "Turns on the chatbots ability to verbally speak it's response to the user. To turn it on click the button labeled on. To turn it off click the button labeled off.",
        "section": "settings_menu",
        "key": "enable_audio"
    },
    {
        "type": "numeric",
        "title": "Increase rate of speech",
        "desc": "Increase the chatbots rate of speech by the number that you supply. If you set this to 40, you've increased the rate by 40 words per minute spoken. Which means if you want to lower the rate by 40, you need to input 40 in the 'Decrease rate of speech' box. ",
        "section": "settings_menu",
        "key": "increase_rate_of_speech"
    },
     {
        "type": "numeric",
        "title": "Decrease rate of speech",
        "desc": "Decrease the chatbots rate of speech by the number that you supply. If you set this to 40, you've decreased the rate by 40 words per minute spoken. Which means if you want to increase the rate by 40, you need to input 40 in the 'Increase rate of speech' box. ",
        "section": "settings_menu",
        "key": "decrease_rate_of_speech"
    },
    {
        "type": "bool",
        "title": "Enable Voice",
        "desc": "Allows the user the ability to use their microphone to speak with the chatbot. To turn it on click the button labeled on. To turn it off click the button labeled off",
        "section": "settings_menu",
        "key": "enable_voice"
    },
    {
        "type": "string",
        "title": "Print File",
        "desc": "To Locate and select a file to print, simply type 'print file' into this box and then click the okay button. This will open a file browser for you to navigate to and select a file to print. Please note that the file will not print untill after the program has closed.",
        "section": "settings_menu",
        "key": "get_file_printed"
    },
    {
        "type": "string",
        "title": "Delete File",
        "desc": "To locate and select a file to delete simply type 'delete file' into the text box and then click okay. This will open a file browser which will allow you to navigate to and select a file for deletion.",
        "section": "settings_menu",
        "key": "get_file_deleted"
    },
    {
        "type": "string",
        "title": "Delete All Files",
        "desc": "To delete all files and folders generated by this program, simply type the text 'delete all' into the box and then click okay. Note: Deleting all files and folders generated by this program will cause the program to exit. To re-generate these files just run the program again.",
        "section": "settings_menu",
        "key": "delete_everything"
    },
    {
        "type": "string",
        "title": "Enter username",
        "desc": "Create a username if you want to, by entering it into this box and clicking the okay button when prompted. You're free to enter what ever you want even if it's a joke. However, being truthful may give more meaning to your conversation.",
        "section": "settings_menu",
        "key": "create_user"
    },
    {
        "type": "string",
        "title": "Enter Gender",
        "desc": "Enter your gender if you want to, by typing it into this box and clicking the okay button when prompted. You're free to enter what ever you want even if it's a joke. However, being truthful may give more meaning to your conversation.",
        "section": "settings_menu",
        "key": "create_gender"
    },
    {
        "type": "string",
        "title": "Enter your age",
        "desc": "Enter your age if you want to, by typing it into this box and clicking the okay button when prompted. You're free to enter what ever you want even if it's a joke. However, being truthful may give more meaning to your conversation.",
        "section": "settings_menu",
        "key": "create_age"
    },
    {
        "type": "string",
        "title": "Clear Conversation Logs",
        "desc": "If you wish to clear the text in the large box labeled 'Conversation log', simply type the word 'yes' into this box and then click the okay button. To do this again simply click on this section, delete the text click okay, then re-type the word 'yes'. This is a security precausion",
        "section": "settings_menu",
        "key": "clear_screen"
    },
    {
        "type": "string",
        "title": "Write User Conversation",
        "desc": "If you'd like to write a text file that contains your entire conversation with the chatbot. Just type 'write file' into this text box and then click the okay button. The file will be named either User_Conversations.txt or, if you gave a username, Username_Conversation.txt. Where Username is the name that you supplied.",
        "section": "settings_menu",
        "key": "write_user_data"
    },
])
